import type { PayrollExecution, PayrollPreview } from "@/lib/payroll/types";

export const payrollPreviewFixture: PayrollPreview = {
  id: "preview_tempo_may",
  tenantId: "000000000003V",
  status: "partially_ready",
  createdAt: "2026-05-03T14:10:00.000Z",
  totals: {
    totalAmounts: [
      {
        amountUnits: "6500000",
        tokenSymbol: "USDC",
        display: "6,500 USDC",
      },
    ],
    totalBlockers: 4,
    totalEmployees: 7,
    employeesReady: 3,
    employeesBlocked: 4,
  },
  items: [
    {
      employeeId: "employee_ana",
      identifier: "EMP-001",
      workerName: "Ana Martinez",
      walletAddress: "0x1234567890AbcdEF1234567890aBcdef12345678",
      amount: {
        amountUnits: "2500000",
        tokenSymbol: "USDC",
        display: "2,500 USDC",
      },
      cadence: "monthly",
      treasury: {
        chain: "tempo-testnet",
        tokenSymbol: "USDC",
        controlMode: "server_controlled",
        matchesDefault: true,
      },
      blockers: [],
    },
    {
      employeeId: "employee_mateo",
      identifier: "EMP-002",
      workerName: "Mateo Rivera",
      walletAddress: "0x78dE345a991247cD5b8a7443F39FfA4282D05044",
      amount: {
        amountUnits: "1750000",
        tokenSymbol: "USDC",
        display: "1,750 USDC",
      },
      cadence: "biweekly",
      treasury: {
        chain: "tempo-testnet",
        tokenSymbol: "USDC",
        controlMode: "user_delegated",
        matchesDefault: true,
      },
      blockers: [],
    },
    {
      employeeId: "employee_lila",
      identifier: "EMP-003",
      workerName: "Lila Chen",
      walletAddress: "0xb794f5ea0ba39494ce839613fffba74279579268",
      amount: {
        amountUnits: "2250000",
        tokenSymbol: "USDC",
        display: "2,250 USDC",
      },
      cadence: "monthly",
      treasury: {
        chain: "tempo-testnet",
        tokenSymbol: "USDC",
        controlMode: "server_controlled",
        matchesDefault: true,
      },
      blockers: [],
    },
    {
      employeeId: "employee_bruno",
      identifier: "EMP-004",
      workerName: "Bruno Silva",
      walletAddress: null,
      amount: {
        amountUnits: "1900000",
        tokenSymbol: "USDC",
        display: "1,900 USDC",
      },
      cadence: "monthly",
      treasury: {
        chain: "tempo-testnet",
        tokenSymbol: "USDC",
        controlMode: "server_controlled",
        matchesDefault: true,
      },
      blockers: ["missing_wallet"],
    },
    {
      employeeId: "employee_carla",
      identifier: "EMP-005",
      workerName: "Carla Gomez",
      walletAddress: "0x0aD4c8e681D47d1b50698a2f8E88B713048bB3C4",
      amount: null,
      cadence: "monthly",
      treasury: {
        chain: "tempo-testnet",
        tokenSymbol: "USDC",
        controlMode: "server_controlled",
        matchesDefault: true,
      },
      blockers: ["missing_active_compensation_profile"],
    },
    {
      employeeId: "employee_diego",
      identifier: "EMP-006",
      workerName: "Diego Ramos",
      walletAddress: "0xCA35b7d915458EF540aDe6068dFe2F44E8fa733c",
      amount: {
        amountUnits: "1000000",
        tokenSymbol: "pathUSD",
        display: "1,000 pathUSD",
      },
      cadence: "weekly",
      treasury: {
        chain: "tempo-testnet",
        tokenSymbol: "USDC",
        controlMode: "server_controlled",
        matchesDefault: false,
      },
      blockers: ["token_mismatch"],
    },
    {
      employeeId: "employee_elena",
      identifier: "EMP-007",
      workerName: "Elena Park",
      walletAddress: "0x6Ecbe1DB9EF729CBe972C83Fb886247691Fb6beb",
      amount: {
        amountUnits: "1200000",
        tokenSymbol: "USDC",
        display: "1,200 USDC",
      },
      cadence: "custom",
      treasury: {
        chain: "tempo-testnet",
        tokenSymbol: "USDC",
        controlMode: "user_signature_required",
        matchesDefault: true,
      },
      blockers: ["treasury_requires_user_signature"],
    },
  ],
};

export const payrollExecutionFixture: PayrollExecution = {
  id: "payrun_tempo_may",
  previewId: payrollPreviewFixture.id,
  status: "queued",
  createdAt: "2026-05-03T14:12:00.000Z",
  readyPaymentCount: 3,
  attempts: [
    {
      id: "attempt_ana",
      employeeId: "employee_ana",
      workerName: "Ana Martinez",
      amount: {
        amountUnits: "2500000",
        tokenSymbol: "USDC",
        display: "2,500 USDC",
      },
      status: "queued",
      label: "In transit",
      transactionHash: null,
    },
    {
      id: "attempt_mateo",
      employeeId: "employee_mateo",
      workerName: "Mateo Rivera",
      amount: {
        amountUnits: "1750000",
        tokenSymbol: "USDC",
        display: "1,750 USDC",
      },
      status: "queued",
      label: "In transit",
      transactionHash: null,
    },
    {
      id: "attempt_lila",
      employeeId: "employee_lila",
      workerName: "Lila Chen",
      amount: {
        amountUnits: "2250000",
        tokenSymbol: "USDC",
        display: "2,250 USDC",
      },
      status: "queued",
      label: "In transit",
      transactionHash: null,
    },
  ],
};
